version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    command: sh -c "cd packages/backend && node server.js"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
      - "8545:8545"
    depends_on:
      - backend
    command: sh -c "\
      yarn install --ignore-scripts && \
      yarn chain & \
      yarn deploy && \
      yarn start"
