[package]
name = "wasm-data-processor"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "wasm-data-processor"
path = "src/lib.rs"
